In [1]:
from scipy.optimize import curve_fit
import numpy as np
import matplotlib.pyplot as plt

In [28]:
def data_generator(num_data):
    a = np.random.rand(num_data).astype('float32')
    b = np.random.rand(num_data).astype('float32')
    c = np.random.rand(num_data).astype('float32')
    d = np.random.rand(num_data).astype('float32')
    return a,b,c,d

def function1(a,b,c,d):
    return 2*a+3*b+5*c+7*d

def function2(a,b,c,d):
    return np.sin(a)*np.cos(b)*np.sin(c)*np.cos(d)

def function3(a,b,c,d):
    return a + np.power(b,c)*d

def function4(a,b,c,d):
    return a*b*c*d
    
def train_test_split(input_matrix, Y):
    num_data = Y.shape[0]
    num_train = round(num_data*.9)
    num_test = round(num_data*.1)
    return input_matrix[:num_train], Y[:num_train], input_matrix[-num_test:], Y[-num_test:]

def scipy_curve_fit_func1(X, k1, k2, k3, k4):
    a,b,c,d = X
    return k1*a+k2*b+k3*c+k4*d

def scipy_curve_fit_func1(X, k1, k2, k3, k4):
    a,b,c,d = X
    return k1*k2*k3*k4*np.sin(a)*np.cos(b)*np.sin(c)*np.cos(d)
    
def plot_y_vs_y_predicted(y_pred, y_test):
    plt.scatter(y_test, y_pred)
    plt.show()

In [19]:
num_data = 10000
a,b,c,d = data_generator(num_data)
input_matrix = np.stack((a, b, c, d), axis=-1)
Y = function1(a,b,c,d)

In [30]:
train_input, train_output, test_input, test_output = train_test_split(input_matrix, Y)
# print (train_input, train_output)
params, params_cov = curve_fit(scipy_curve_fit_func1, (train_input[:,0], train_input[:,1], train_input[:,2], train_input[:,3]), train_output)
print(params)
print(params_cov)

[2.64942377 1.97480746 2.57587486 2.57648116]
[[-1.66577584e+13  1.19198858e+10  4.33358021e+12  1.18403207e+13]
 [ 1.59486969e+13  6.31509969e+12  5.44036469e+10 -2.37728718e+13]
 [ 1.83314157e+13  4.19040123e+12 -1.16582066e+13 -1.16133637e+13]
 [-2.28960744e+13 -1.24201677e+13  7.37309327e+12  3.10446369e+13]]
